In [2]:
import numpy as np

## Basic NumPy Array operations

In [3]:
L = [1,2,3]

In [4]:
A = np.array([1,2,3])

In [5]:
for e in L:
  print(e)

1
2
3


In [6]:
for e in A:
  print(e)

1
2
3


In [8]:
L.append(4)
print(L)

[1, 2, 3, 4, 4]


In [ ]:
# that does not work on an array - arrays are fixed length!

In [9]:
L + [5]

[1, 2, 3, 4, 4, 5]

In [10]:
A + np.array([4])
# this adds 4 to each element in the array!
# the plus is an actual math operations, not a concat

array([5, 6, 7])

In [11]:
# vector addition
A + np.array([4,5,6])

array([5, 7, 9])

In [12]:
# scalar multiplication
2 * A

array([2, 4, 6])

In [13]:
# multiply does repetition for lists
2 * L

[1, 2, 3, 4, 4, 1, 2, 3, 4, 4]

In [16]:
# do scalar multiplication without numpy
L2 = []
for e in L:
  L2.append(e+3)

In [17]:
L2

[4, 5, 6, 7, 7]

In [ ]:
# or via list comprehension
L2 = [e + 3 for e in L]

In [18]:
# square all elements without numpy
L2 = []
for e in L:
  L2.append(e**2)

In [19]:
# with numpy:
A**2

array([1, 4, 9])

## Dot Product

In [ ]:
# define the vectors
a = np.array([1,2])
b = np.array([3,4])

In [21]:
# dot product with only basic Python
dot = 0
for e, f in zip(a, b):
  dot += e*f
dot

11

In [23]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [25]:
a* b
np.sum(a*b)

11

In [26]:
(a*b).sum()

11

In [ ]:
# use the actual dot function
np.dot(a, b)
# equivalent:
a.dot(b)

In [27]:
# and even more different options!
a @ b

11

In [28]:
# use the cosine definition of the dot product:
# a^T b = magn(a) magn(b) cos(theta)
amag = np.sqrt((a*a).sum())

In [29]:
# use built in function to calculate magnitude of a
np.linalg.norm(a)

2.23606797749979

In [30]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [31]:
cosangle

0.9838699100999074

In [32]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

## Matrices

In [33]:
# without numpy
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [34]:
L[0][1]

2

In [35]:
# with numpy
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [36]:
A[0][1]

2

In [37]:
A[0,1]

2

In [38]:
# access whole column
A[:,0]

array([1, 3])

In [39]:
A.T

array([[1, 3],
       [2, 4]])

In [40]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [41]:
# same with list instead of array
# this "knows" a list of lists is an array and treats it as such
# even returns numpy array
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [43]:
B = np.array([[1,2,3], [4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
# matrix multiplication (not! elementwise)
# matrix multiplication is extension of dot product
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [45]:
A.dot(B.T)

ValueError: ignored

In [46]:
# determinant
np.linalg.det(A)

-2.0000000000000004

In [47]:
# inverse
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [48]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [49]:
# trace
np.trace(A)

5

In [50]:
np.diag(A)

array([1, 4])

In [51]:
# Create a diagonal matrix with 1,4 on the diagonal
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [52]:
# eigenvalues
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [54]:
# check with eigenvalue * eigenvector = matrix * eigenvector
Lam, V = np.linalg.eig(A)

In [55]:
V[:,0] * Lam[0] == A @ V[:,0]
# this returns one false because of numerical precision

array([ True, False])

In [58]:
# correct way to compare two arrays
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

True

In [59]:
np.allclose(V @ np.diag(Lam), A @ V)

True

## Solving linear system

In [61]:
A = np.array([[1,1], [1.5,4]])
b = np.array([2200, 5050])

In [62]:
np.linalg.solve(A, b) # good way

array([1500.,  700.])

In [63]:
np.linalg.inv(A).dot(b) # bad way: slow, inaccurate

array([1500.,  700.])

## Generating data

In [64]:
# create array of all zeros, 2x3
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
# same with ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [68]:
10 * np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [69]:
# create identity matrix: eye is homophone to I (short for identity)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
# create array of random numbers between 0 and 1
np.random.random((2,3))

array([[0.52393992, 0.37248   , 0.32421508],
       [0.79936017, 0.12863481, 0.47644159]])

In [71]:
# create array of random numbers from normal distribution
np.random.randn(2,3)

array([[-1.13886943,  0.39220692,  0.76065806],
       [-0.24385073, -1.15728859,  0.69883885]])

In [72]:
# try out on large array
R = np.random.randn(10000)

In [73]:
R.mean()

-0.008115110533384111

In [74]:
np.mean(R)

-0.008115110533384111

In [75]:
R.var()

0.9867670552583225

In [76]:
R.std()

0.9933614927398396

In [78]:
# with matrix
R = np.random.randn(10000,3)

In [79]:
R.mean(axis=0) # along colums

array([-0.00914079, -0.00606007,  0.00980136])

In [80]:
R.mean(axis=1) # along rows

array([ 0.17597726, -0.42008154,  0.37136501, ...,  0.53401854,
       -0.32855467, -0.1500511 ])

In [81]:
# covariance (analog for variance on vectors)
np.cov(R) # this is column wise

array([[ 3.78578512, -0.53062621,  0.45650991, ...,  3.39518191,
         1.39937938,  2.78387211],
       [-0.53062621,  0.0743846 , -0.06440245, ..., -0.47491129,
        -0.19554334, -0.39068943],
       [ 0.45650991, -0.06440245,  0.07151006, ...,  0.37121625,
         0.14513976,  0.35521295],
       ...,
       [ 3.39518191, -0.47491129,  0.37121625, ...,  3.1334902 ,
         1.3097619 ,  2.45135666],
       [ 1.39937938, -0.19554334,  0.14513976, ...,  1.3097619 ,
         0.55111464,  1.00104307],
       [ 2.78387211, -0.39068943,  0.35521295, ...,  2.45135666,
         1.00104307,  2.0702608 ]])

In [82]:
np.cov(R).shape

(10000, 10000)

In [83]:
np.cov(R.T)

array([[ 1.0095698 , -0.00116714, -0.00151617],
       [-0.00116714,  1.00675892, -0.00306727],
       [-0.00151617, -0.00306727,  1.00998421]])

In [84]:
# create array of random integers
np.random.randint(0,10,size=(3,3))

array([[0, 2, 2],
       [3, 8, 5],
       [5, 3, 5]])

In [85]:
# select random sample
np.random.choice(10, size=(3,3))

array([[5, 2, 9],
       [8, 8, 1],
       [2, 0, 9]])